# Generated by Django 4.2.13 on 2024-05-08 09:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0192_merge_20240405_1154"),
        ("discount", "0081_merge_20240422_1207"),
    ]

    operations = [
        migrations.AlterField(
            model_name="promotionrule",
            name="gifts",
            field=models.ManyToManyField(
                blank=True, related_name="+", to="product.productvariant"
            ),
        ),
    ]
